# candidate_labels = ['Additional Payment',
#                     'Appeal Decision',
#                     'Application Status',
#                     'Award letter',
#                     'Back Pay',
#                     'Benefits Increase',
#                     'Benefits Information',
#                     'Benefits Status',
#                     'Benefits Update',
#                     'Benefits Switch',
#                     'Benefits denied',
#                     'Books and supplies Allowance',
#                     'Career counseling',
#                     'Certificate Reimbursement',
#                     'Certificate of Eligibility (COE)',
#                     'Compliance Survey',
#                     'Correction to benefits statement',
#                     'Debt Accrual',
#                     'Debt Discrepancy',
#                     'Debt Letter',
#                     'Debt Waiver',
#                     'Decision Letter',
#                     'Denial letter',
#                     'Dependent Benefits',
#                     'Disenroll from program',
#                     'Document Submission',
#                     'Education Benefits',
#                     'Education Benefits Eligibility',
#                     'Enrollment Verification',
#                     'Entitlement Documentation',
#                     'Explanation of Debt',
#                     'Fry Scholarship',
#                     'Fraudulent School',
#                     'GI Bill',
#                     'Hazelwood Act',
#                     'Housing Allowance/BAH',
#                     'International Student',
#                     'Late Enrollment Certification',
#                     'Lost Certification Search',
#                     'Montgomery GI Bill/MGIB',
#                     'Missing Payment',
#                     'Payment Details',
#                     'Payment correction',
#                     'Post 9/11',
#                     'Reinstatement of benefits',
#                     'Remaining Benefits',
#                     'Remove dependent from benefits',
#                     'Request for Appeal',
#                     'Request for Assistance',
#                     'Request for Benefit Rating Information',
#                     'Request for Benefits Extension',
#                     'Request for Benefits Information',
#                     'Request for Documents',
#                     'Request for Eligibility Information',
#                     'Request for Enrollment Status',
#                     'Request for Payment Assistance',
#                     'Request for Reassessment',
#                     'Request for Reconsideration of Payments',
#                     'Request for application status',
#                     'Request for payment',
#                     'Request to Relinquishing Benefits',
#                     'Request to set Benefit start date',
#                     'Request to update Date of Birth',
#                     'Request to update application',
#                     'Request to update Contact Information',
#                     'Requesting Refund',
#                     'Retro Certification',
#                     'STEM scholarship',
#                     'STEM scholarship application',
#                     'School Change Form',
#                     'Self Service Issue - AVA',
#                     'Self Service Issue - VA.gov',
#                     'Self Service down',
#                     'Statement of Benefits (SOB)',
#                     'Transfer of Benefits',
#                     'VA website down',
#                     'VET TEC',
#                     'VR&E',
#                     'VRRAP',
#                     'VRRAP Representative',
#                     'VRRAP letter']
candidate_labels = ['Award letter',
                    'Back Pay',
                    'Certificate of Eligibility (COE)',
                    'Compliance Survey',
                    'Correction to benefits statement',
                    'Debt Discrepancy',
                    'Decision Letter',
                    'Denial letter',
                    'Dependent Benefits',
                    'Explanation of Debt',
                    'Fraudulent School',
                    'GI Bill',
                    'Hazelwood Act',
                    'Housing Allowance/BAH',
                    'Montgomery GI Bill/MGIB',
                    'Missing Payment',
                    'Payment Details',
                    'Post 9/11',
                    'Reinstatement of benefits',
                    'Remaining Benefits',
                    'Remove dependent from benefits',
                    'Request for Appeal',
                    'Request for Assistance',
                    'Request for Benefit Rating Information',
                    'Request for Benefits Extension',
                    'Request for Benefits Information',
                    'Request for Documents',
                    'Request for Eligibility Information',
                    'Request for Enrollment Status',
                    'Request for application status',
                    'Request for payment',
                    'Request to update application',
                    'Request to update Contact Information',
                    'Requesting Refund',
                    'STEM scholarship',
                    'Self Service down',
                    'Statement of Benefits (SOB)',
                    'Transfer of Benefits',
                    'VA website down',
                    'VET TEC']

candidate_sents = ["Neutral", "Angry", "Happy", "Frustrated", "Concerned"]
